eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.33.66:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
    ip-address: 180.76.159.181
    #hostname: clientHostName
